<?php

$this->headTitle($this->sitemapPage['title']);

?>
        <main class="bookMain">
			
            <?php echo $this->breadCrumbsHtml($this->sitemapPage['id']);?>

            <!--******************************************
                     MAIN PRODUCTS-SORTING START
            ******************************************-->
            <div class="productSorting text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <article>
                                <a href="javascript:void(0)" class="filterProduct">FILTER PRODUCT <span class="fa fa-bars"></span></a>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <p><strong><?php echo count($this->books);?></strong> results in books</p>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <form class="sorting">
                                    <select class="text-uppercase">
                                        <option selected="">DEFALUT SORTING</option>
                                        <option>Po ceni</option>
                                        <option>Po autoru</option>
                                        <option>Po izdavacu</option>
                                        <option>Po zanru</option>
                                    </select>
                                </form>

                            </article>
                        </div>
                    </div>
                </div>
            </div>
            <!--******************************************
                     MAIN PRODUCTS-SORTING END
            ******************************************-->
            <section class="filter-wrapper">
                <form class="formFilter">

                    <p class="firstTitle"><b>FILTER</b></p>
                    <div id="slider-range"></div>
                    <ul class="list-unstyled productCategories">    
                        <li class="titleProduct"><strong>BOOK CATEGORIES</strong><hr>
                        <?php foreach ($this->categories as $category) {?>
                            <li><?php echo $this->escape($category['title']);?></li>
                        <?php }?>
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titleProduct"><strong>COVER</strong><hr>
                        <?php foreach($this->covers as $cover) {?>
                        <li><?php echo $this->escape($cover['title']);?> <span class="priceAuthor"></span></li>
                        <?php }?>
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><strong>AUTHOR</strong><hr>
                        <?php foreach($this->authors as $author) {?>
                        <li><?php echo $this->escape($author['name']);?> <span class="priceAuthor"></span></li>
                        <?php }?>
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><strong>LANGUAGE</strong><hr>
                        <?php foreach($this->languages as $language) {?>
                        <li><?php echo $this->escape($language['title']);?> <span class="priceAuthor"></span></li>
                        <?php }?>
                    </ul>
                </form>
            </section>
			<hr>



            <!--******************************************
                            MAIN BESTSELLERS START
             ******************************************-->
            <div class="container">
                <div class="bestsellers clearfix text-center">
                    <h2>All Books</h2>
                    <?php foreach ($this->books as $book) { ?>
                        <div class="books">
                            <figure class="center-block">
                                <a href="<?php echo $this->bookUrl($book); ?>"><img src="<?php echo $this->bookImgUrl($book); ?>" class="img-responsive"></a>
                                <?php if ($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) { ?>
                                    <span class="sale">SALE</span>
                                <?php } ?>
                            </figure>
                            <h4 class="down"><a href="<?php echo $this->bookUrl($book); ?>"><b><?php echo $this->escape($book['title']); ?></b></a></h4>
                            <p><span class="by">by</span>
                                <?php
                                foreach ($this->authors as $author) {
                                    if ($author['id'] == $book['author_id']) {
                                        echo $author['name'];
                                    }
                                }
                                ?>
                            </p>
                            <p class="prise center-block"><?php echo $this->escape($book['price']); ?><!--<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a>--></p>
                        </div>
                    <?php } ?>
                </div>
            </div>

            <!--******************************************
                             MAIN BESTSELLERS END
              ******************************************-->
    
        </main>
        <!--******************************************
        **********************************************
                            MAIN END
        *********************************************
        *********************************************-->

