<!--******************************************
        **********************************************
                        MAIN START
        *********************************************
        ******************************************-->
        <main>

            <ol class="breadcrumb text-center">
                <li><a href="#">Home</a></li>
                <li><b>Books</b></li>
            </ol>

            <!--******************************************
                            MAIN SLIDER START
             ******************************************-->
            <div class="slider">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">

                            <img src="/front/img/sliderBooks.png">
                            <div class="carousel-caption">
                                <h2><b>Hezy Theme:</b> What We Can All Do to Save America's Future</h2>
                                <a href="#">VIEW MORE</a>
                            </div>
                        </div>
                        <div class="item">
                            <img src="/front/img/sliderBooks.png">
                            <div class="carousel-caption">
                                <h2><b>Hezy Theme:</b> What We Can All Do to Save America's Future</h2>
                                <a href="#">VIEW MORE</a>
                            </div>
                        </div>
                        <div class="item">
                            <img src="/front/img/sliderBooks.png">
                            <div class="carousel-caption">
                                <h2><b>Hezy Theme:</b> What We Can All Do to Save America's Future</h2>
                                <a href="#">VIEW MORE</a>
                            </div>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <!--******************************************
                          MAIN SLIDER END
             ******************************************-->




            <!--******************************************
                     MAIN PRODUCTS-SORTING START
            ******************************************-->
            <div class="productSorting text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <article>
                                <a href="javascript:void(0)" class="filterProduct">FILTER PRODUCT <span class="fa fa-bars"></span></a>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <p>34,231 results in books</p>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <form class="sorting">
                                    <select class="text-uppercase">
                                        <option selected="">DEFALUT SORTING</option>
                                        <option>Po ceni</option>
                                        <option>Po autoru</option>
                                        <option>Po izdavacu</option>
                                        <option>Po zanru</option>
                                    </select>
                                </form>

                            </article>
                        </div>
                    </div>
                </div>
            </div>
            <!--******************************************
                     MAIN PRODUCTS-SORTING END
            ******************************************-->
            <section class="filter-wrapper">
                <form class="formFilter">

                    <p class="firstTitle"><b>FILTER</b></p>
                    <div id="slider-range"></div>
                    <p>
                        <label for="amount">Price</label>
                        <input type="text" id="amount" readonly style="border:0; color:#000;">
                    </p>
                    <ul class="list-unstyled productCategories">    
                        <li class="titleProduct"><a href="#">PRODUCT CATEGORIES</a>
                        <li><a href="#">Books</a></li>
                        <li><a href="#">Textbooks</a></li>
                        <li><a href="#">Audiobooks</a></li>
                        <li><a href="#">Magazines</a></li>
                        <li><a href="#">Movies</a></li>
                        <li><a href="#">Music</a></li>
                        <li><a href="#">Games</a></li>
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><a href="#">New Releases</a>
                        <li><a href="#">Last 30 days <span class="priceReleases">100,358</span></a></li>
                        <li><a href="#">Last 90 days <span class="priceReleases">100,358</span></a></li>
                        <li><a href="#">Coming Soon <span class="priceReleasesLast">100,358</span></a></li>                       
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><a href="#">FORMAT</a>
                        <li><a href="#">Paperback <span class="priceFormat">100,358</span></a></li>
                        <li><a href="#">Hardcover <span class="priceFormat">100,358</span></a></li>
                        <li><a href="#">Kindle Edition <span class="priceFormat">100,358</span></a></li>
                        <li><a href="#">Audible Audtio Edition <span class="priceFormat">100,358</span></a></li>
                        <li><a href="#">Printed Access Code <span class="priceFormat">100,358</span></a></li>
                        <li><a href="#">Audio CD <span class="priceFormat">100,358</span></a></li> 
                        <li><a href="#">Board Boak <span class="priceFormat">100,358</span></a></li>
                    </ul>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><a href="#">AUTHOR</a>
                        <li><a href="#">John Green <span class="priceAuthor">288</span></a></li>
                        <li><a href="#">J.J. Smith <span class="priceAuthor">3</span></a></li>
                        <li><a href="#">Laura Hillenbrand <span class="priceAuthor">5</span></a></li>
                        <li><a href="#">George R.R. Martin <span class="priceAuthor">377</span></a></li>
                        <li><a href="#">Dean Koontz <span class="priceAuthor">260</span></a></li>
                        <li><a href="#">Edward Klein <span class="priceAuthor">4</span></a></li> 
                        <li><a href="#">Donna Tartt <span class="priceAuthor">5</span></a></li>
                    </ul>
                    <p><a href="#" class="arrowRightAuthor">See all <span class="fa fa-arrow-right"></span></a>  </p>
                    <ul class="list-unstyled productCategories">    
                        <li class="titles"><a href="#">LENGUAGE</a>
                        <li><a href="#">ENGLISH <span class="priceAuthor">18,610,000</span></a></li>
                        <li><a href="#">GERMAN <span class="priceAuthor">2,199,573</span></a></li>
                        <li><a href="#">FRANCE <span class="priceAuthor">2,185,922</span></a></li>
                        <li><a href="#">SPANISH <span class="priceAuthor">1,171,681</span></a></li>
                        <li><a href="#">ITALY <span class="priceAuthor">804,936</span></a></li>
                        <li><a href="#">UKRAINIAN Klein <span class="priceAuthor">910,814</span></a></li> 
                        <li><a href="#">CHINESE <span class="priceAuthor">562,811</span></a></li>
                    </ul>
                    <p><a href="#" class="arrowRightAuthor">See all <span class="fa fa-arrow-right"></span></a>  </p>
                </form>
            </section>



            <!--******************************************
                            MAIN BESTSELLERS START
             ******************************************-->
            <div class="container">
                <div class="bestsellers clearfix text-center">
                    <h2>Books for Subjects</h2>
                    <div class="arrowRight">
                        <p class="text-center"><a href="#">See all <span class="fa fa-arrow-right"></span></a></p>
                    </div>
                    <div class="booksFirst firstBook">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookGreen.png" class="img-responsive"></a>                     
                        </figure>                  
                        <h4><a href="#">Art, Architecture & Photography</a></h4>
                        <p class="nameOfBook">310 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookOrange.png" class="img-responsive"></a>
                        </figure>
                        <h4><a href="#">Bible & Bible Studies</a></h4>
                        <p class="nameOfBook">199 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookLightOrange.png" class="img-responsivek"></a>
                        </figure>                         
                        <h4><a href="#">Biographies</a></h4>
                        <p class="nameOfBook">1 921 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/redBook.png" class="img-responsive"></a>
                        </figure>                         
                        <h4><a href="#">Business & Money></a></h4>
                        <p class="nameOfBook">466 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookYellow.png" class="img-responsive"></a>
                        </figure>                         
                        <a href="#"><h4>Business & Money</a></h4>
                        <p class="nameOfBook">466 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookLightOrange.png" class="img-responsive"></a>                     
                        </figure>                  
                        <h4><a href="#">Children's Books</a></h4>
                        <p class="nameOfBook">410 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookYellow.png" class="img-responsive"></a>
                        </figure>
                        <h4><a href="#">Commputing & Internet</a></h4>
                        <p class="nameOfBook">774 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookBlack.png" class="img-responsivek"></a>
                        </figure>                         
                        <h4><a href="#">Cookbooks, Food & Wine</a></h4>
                        <p class="nameOfBook">51 items</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookGreen.png" class="img-responsive"></a>
                        </figure>
                        <h4><a href="#">Crafts & Hobbies</a></h4>                                         
                        <p class="nameOfBook">Hezy Theme</p>
                    </div>
                    <div class="booksFirst">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/redBook.png" class="img-responsive"></a>
                        </figure>                         
                        <h4><a href="#">Crafts & Hobbies</a></h4>
                        <p class="nameOfBook">Georgy Berns</p>
                    </div>         
                </div>            
            </div>

            <div class="container">
                <div class="bestsellers clearfix text-center">
                    <h2>Bestsellers</h2>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookOrange.png" class="img-responsive"></a>
                            <span class="sale">SALE</span>
                        </figure>                  
                        <h4><a href="#">The Brief Wondrous Life of Oscar Wao</a></h4>
                        <p><span class="by">by</span> Cormac McCartny</p>
                        <p class="prise center-block">$1,401.75<a class="shop" href="#"><span ><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookGreen.png" class="img-responsive"></a>
                        </figure>
                        <h4 class="down"><a href="#"><b>Doctor Sleep</b></a></h4>
                        <p><span class="by">by</span> Stephen King</p>
                        <p class="prise center-block">$14.15<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookBlack.png" class="img-responsivek"></a>
                        </figure>                         
                        <h4 class="down"><a href="#"><b>Wonder Hardcover</b></a></h4>
                        <p><span class="by">by</span> R.J. Palacio</p>
                        <p class="prise center-block">$9.59<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookYellow.png" class="img-responsive"></a>
                            <span class="sale">SALE</span>
                        </figure>                         
                        <h4><a href="#">The Brief Wondrous Life of Oscar</a></h4>
                        <p><span class="by">by</span> Hezy Theme</p>
                        <p class="prise center-block">$12.00<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books lastBook">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookGreen.png" class="img-responsive"></a>
                        </figure>                         
                        <h4><a href="#">How Dogs Love Us: A Neuroscientist and His Dog</a> </h4>
                        <p><span class="by">by</span> Georgy Berns</p>
                        <p class="prise center-block last">$7.95<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookLightOrange.png" class="img-responsive"></a>
                        </figure>                  
                        <h4 class="down"><a href="#">From Kant to Husserl</a></h4>
                        <p><span class="by">by</span> Cormac McCartny</p>
                        <p class="prise center-block">$101.00<a class="shop" href="#"><span ><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookOrange.png" class="img-responsive"></a>
                        </figure>
                        <h4 class="down"><b><a href="#">Doctor Sleep</a></b></h4>
                        <p><span class="by">by</span> Stephen King</p>
                        <p class="prise center-block">$19.45<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookGreen.png" class="img-responsivek"></a>
                        </figure>                         
                        <h4 class="down"><a href="#"><b>Wonder Hardcover</b></a></h4>
                        <p><span class="by">by</span> R.J. Palacio</p>
                        <p class="prise center-block">$17.11<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookOrange.png" class="img-responsive"></a>
                        </figure>                         
                        <h4><a href="#">The Brief Wondrous Life of Oscar</a></h4>
                        <p><span class="by">by</span> Hezy Theme</p>
                        <p class="prise center-block">$14.65<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                    <div class="books lastBook">
                        <figure class="center-block">
                            <a href="#"><img src="/front/img/books/bookOrange.png" class="img-responsive"></a>
                        </figure>                         
                        <h4 class=" aaa"><a href="#">How Dogs Love Us: A Neuroscientist and His Dog</a> </h4>
                        <p><span class="by">by</span> Georgy Berns</p>
                        <p class="prise center-block last">$9.95<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket""></span></span></a></p>
                    </div>
                </div>
            </div>

            <!--******************************************
                             MAIN BESTSELLERS END
              ******************************************-->



            <!--******************************************
                           MAIN TESTIOMONIALS START
            ******************************************-->
            <div class="testimonials">
                <div class="container">
                    <h1 class="text-center">Customer testimonials</h1>
                    <div class="row">
                        <div class="col-sm-6">
                            <article>
                                <div class="image ballon center-block">
                                    <span class="fa fa-quote-right"></span>  
                                    <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>                                   
                                </div>   
                                <div class="ava">
                                    <img src="/front/img/member1.png" class="img-responsive">
                                </div>
                                <div class="cocaCola">
                                    <h2>Philip Antony Hopking</h2>
                                    <h3>Coca-Cola</h3>     
                                </div>                         
                            </article>
                        </div>
                        <div class="col-sm-6">
                            <article>
                                <div class="image ballon center-block">
                                    <span class="fa fa-quote-right"></span>  
                                    <p>Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam</p>                   
                                </div>                       
                                <div class="ava">
                                    <img src="/front/img/member2.png" class="img-responsive">
                                </div>
                                <div class="apple">
                                    <h2>Steve Jobs</h2>
                                    <h3>Apple</h3>     
                                </div>                             
                            </article>
                        </div>
                    </div>
                </div>
            </div>
            <!--******************************************
                            MAIN TESTIOMONIALS END
             ******************************************-->



            <!--******************************************
                           MAIN FROMBLOG START
            ******************************************-->
            <div class="fromBlog">
                <div class="container">
                    <h2 class="text-center">From the blog</h2>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-sm-4">
                                    <article>
                                        <figure>
                                            <a href="#"><img src="/front/img/index-blog-1.png" alt="" class="center-block img-responsive"></a>
                                        </figure>
                                    </article>
                                </div>
                                <div class="col-sm-8 crasDapubus">
                                    <article>
                                        <h3><a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a></h3>
                                        <p class="comment"><a href="#">12 comments</a></p>
                                        <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>
                                    </article>                                   
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-sm-4">
                                    <figure>
                                        <a href="#"><img src="/front/img/index-blog-2.png" alt="" class="center-block img-responsive"></a>
                                        </figure>
                                </div>
                                <div class="col-sm-8 crasDapubus">
                                    <article>
                                        <h3><a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a></h3>
                                        <p class="comment"><a href="#">12 comments</a></p>
                                        <p>Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque</p>
                                    </article>                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            <!--******************************************
                             MAIN FROMBLOG END
              ******************************************-->      
        </main>
        <!--******************************************
        **********************************************
                            MAIN END
        *********************************************
        *********************************************-->

