<?php

$this->headTitle('Languages - Edit Language');

$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));

?>
<div class="page-header">
    <h1>Languages <small>Edit Language</small></h1>
</div>
<div class="row">
    <div class="coll-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="coll-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_languages', 'action' => 'index'), 'default', true) ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i> Back to all languages</a>
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <input type="hidden" name="task" value="update">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Language - <?php echo $this->escape($this->language['title']);?></legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="title">Title</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter title of new language',
                                    'id' => 'title',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 2 max 255 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="new_language_cancel"></label>
                            <div class="col-md-8">
                                <a href="<?php echo $this->url(array('controller' => 'admin_languages', 'action' => 'index'), 'default', true);?>" 
                                   id="new_member_cancel" name="new_language_cancel" class="btn btn-default">Cancel</a>
                                <button type=submit" id="new_member_submit" name="new_language_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>