<!--******************************************
                        MAIN START
        *******************************************-->
        <main>

            <!--******************************************
                            MAIN SLIDER START
             ******************************************-->
            <div class="slider">
				
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                    <!-- Wrapper for slides -->
					
                    <div class="carousel-inner" role="listbox">
						<?php foreach ($this->indexSlides as $index => $indexSlide) {?>
                        <div class="item <?php echo $index == 0 ? 'active' : '';?>">
							<img src="<?php echo $this->indexSlideImgUrl($indexSlide);?>">
                            <div class="carousel-caption">
                                <h2><b></b><?php echo $this->indexSlideLinkUrl($indexSlide);?></h2>
                                <?php if ($indexSlide['link_type'] != 'NoLink') { ?>
									<a href="<?php echo $this->indexSlideLinkUrl($indexSlide);?>" class="btn btn-lg btn-primary"><?php echo $this->escape($indexSlide['link_label']);?></a>
                                <?php } ?>
                            </div>
                        </div>
					<?php } ?>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
				
					
            </div>
            <!--******************************************
                          MAIN SLIDER END
             ******************************************-->


            <!--******************************************
                            MAIN BANNERS START
             ******************************************-->
            <div class="container">
                <div class="banners">
                    <div class="row">
                        <div class="col-md-6 text-center">
                            <article>
                                <div class="bannerContent">
                                    <a href="<?php echo $this->sitemapPageUrl('15');?>"><?php echo $this->sitemapPageShortTitle('15');?></a>
                                    <p>The sale don't stop up to 75% off!</p>
                                </div>
                            </article>
                        </div>
                        <div class="col-md-6 text-center">
                            <article>
                                <div class="bannerContent">
                                    <a href="<?php echo $this->sitemapPageUrl('14');?>"><?php echo $this->sitemapPageShortTitle('14');?></a>
                                    <p>New arrivals</p>
                                </div>
                            </article>
                        </div>
<!--                        <div class="col-md-4 text-center">
                            <article>
                                <div class="bannerContent">
                                    <a href="#">READ THE BLOG</a>
                                    <p>Latest hot news</p>
                                </div>
                            </article>
                        </div>-->
                    </div>
                </div>
            </div>
            <!--******************************************
                            MAIN BANNERS END
             ******************************************-->


            <!--******************************************
                            MAIN BESTSELLERS START
             ******************************************-->
            <div class="container">
                <div class="bestsellers clearfix text-center">
                    <h2>Books</h2>
					<?php foreach($this->books as $book) { ?>
					<div class="books">
                        <figure class="center-block">
                            <a href="<?php echo $this->bookUrl($book);?>"><img src="<?php echo $this->bookImgUrl($book);?>" class="img-responsive"></a>
							<?php if($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) {?>
								<span class="sale">SALE</span>
							<?php }?>
                        </figure>                  
                        <h4><a href="<?php echo $this->bookUrl($book);?>"><?php echo $this->escape($book['title']);?></a></h4>
                        <p><span class="by">by</span> Cormac McCartny</p>
                        <p class="prise center-block"><?php echo $this->escape($book['price']);?><!--<a class="shop" href="#"><span ><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a>--></p>
                    </div>
					<?php }?>
                </div>  
                <p class="text-center"> <a href="<?php echo $this->sitemapPageUrl('2');?>" class="viewMore">VIEW MORE</a></p>
            </div>
            <!--******************************************
                             MAIN BESTSELLERS END
              ******************************************-->



            <!--******************************************
                           MAIN TESTIOMONIALS START
            ******************************************-->
            <div class="testimonials">
                <div class="container">
                    <h1 class="text-center">Customer testimonials</h1>
                    <div class="row">
                        <div class="col-sm-6">
                            <article>
                                <div class="image ballon center-block">
                                    <span class="fa fa-quote-right"></span>  
                                    <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>                                   
                                </div>   
                                <div class="ava">
                                    <img src="/front/img/member1.png" class="img-responsive">
                                </div>
                                <div class="cocaCola">
                                    <h2>Philip Antony Hopking</h2>
                                    <h3>Coca-Cola</h3>     
                                </div>                         
                            </article>
                        </div>
                        <div class="col-sm-6">
                            <article>
                                <div class="image ballon center-block">
                                    <span class="fa fa-quote-right"></span>  
                                    <p>Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam</p>                   
                                </div>                       
                                <div class="ava">
                                    <img src="/front/img/member2.png" class="img-responsive">
                                </div>
                                <div class="apple">
                                    <h2>Steve Jobs</h2>
                                    <h3>Apple</h3>     
                                </div>                             
                            </article>
                        </div>
                    </div>
                </div>
            </div>
            <!--******************************************
                            MAIN TESTIOMONIALS END
             ******************************************-->


            <!--******************************************
                             MAIN LATESTPRODUCT START
              ******************************************-->
            <div class="latestProduct">
                <div class="container">
                    <h2 class="text-center">Latest products</h2>
                    <div class="row">
						<?php foreach($this->shelfBooks as $book) { ?>
                        <div class="col-sm-3">
                            <article>
                                <a href="<?php echo $this->bookUrl($book);?>"><img src="<?php echo $this->bookImgUrl($book);?>" class="img-responsive center-block"></a>
								<?php if($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) {?>
									<span class="sale">SALE</span>
								<?php }?>
                            </article>
                        </div>
						<?php }?>
                    </div>
                </div>
            </div>
            <!--******************************************
                            MAIN LATESTPRODUCT END
             ******************************************-->



            <!--******************************************
                          MAIN TEXT START
           ******************************************-->
            <div class="text">
                <div class="container">
                    <h1 class="text-center">
                        Services
                    </h1>
                </div>            
            </div>
            <!--******************************************
                            MAIN TEXT END
             ******************************************-->



            <!--******************************************
                            MAIN FEATURES START
             ******************************************-->
            <div class="features" id="Services">
                <div class="container">
                    <div class="row">
						<?php foreach ($this->services as $service) {?>
                        <div class=" col-md-6 content">
                            <article class="borderGray">
                                <div class="row ">
                                    <div class=" col-sm-9 ">
                                        <article class="singleJob">
                                            <h4 class="text-uppercase"><?php echo $this->escape($service['title']);?></h4>
                                            <p><?php echo $this->escape($service['description']);?></p>
                                            <!--<a href="#">FIND OUT MORE <span class="fa fa-arrow-right"></span></a>-->
                                        </article>
                                    </div>
                                    <div class=" col-sm-3 text-center">
                                        <article class="boxCircle">
                                            <span class="<?php echo $this->escape($service['icon']);?>"></span>
                                        </article>
                                    </div>
                                </div>
                            </article>
                        </div>
						<?php }?>
                    </div>
                </div>
            </div>
            <!--******************************************
                             MAIN FEATURES END
              ******************************************-->



            <!--******************************************
                           MAIN BOXES START
            ******************************************-->
<!--            <div class="boxes">
                <div class="container">
                    <div class="row text-center block-center">
                        <div class="col-sm-4">
                            <figure>
                                <img src="/front/img/Bookstore.jpg" alt="" class="img-responsive center-block">
                            <article class="articleSale">
                                <h2><a href="#">SALE</a></h2>
                                <p>The sale don't stop up to 75% off!</p>
                            </article>
                            </figure>
                            
                        </div>
                        <div class="col-sm-4">
                            <figure>
                                <img src="/front/img/games.jpg" alt="" class="img-responsive center-block">
                            <article class="articleGames">
                                <h2><a href="#">GAMES</a></h2>
                                <P>The sale don't stop up to 75% off!</P>
                            </article>
                            </figure>
                            
                        </div>
                        <div class="col-sm-4">
                            <figure>
                                <img src="/front/img/loogbook.png" alt="" class="img-responsive center-block">
                            <article class="articleLookBook">
                                <h2><a href="#">LOOKBOOK</a></h2>
                                <P>Take a look at the uncoming trends.</P>
                            </article>
                            </figure>
                            
                        </div>
                    </div>
                </div>
            </div>-->
            <!--******************************************
                             MAIN BOXES END
              ******************************************-->



            <!--******************************************
                           MAIN FROMBLOG START
            ******************************************-->
<!--            <div class="fromBlog">
                <div class="container">
                    <h2 class="text-center">From the blog</h2>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-sm-4">
                                    <article>
                                        <figure>
                                            <a href="#"><img src="/front/img/index-blog-1.png" alt="" class="center-block img-responsive"></a>
                                        </figure>
                                    </article>
                                </div>
                                <div class="col-sm-8 crasDapubus">
                                    <article>
                                        <h3><a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a></h3>
                                        <p class="comment"><a href="#">12 comments</a></p>
                                        <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>
                                    </article>                                   
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-sm-4">
                                    <figure>
                                        <a href="#"><img src="/front/img/index-blog-2.png" alt="" class="center-block img-responsive"></a>
                                        </figure>
                                </div>
                                <div class="col-sm-8 crasDapubus">
                                    <article>
                                        <h3><a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a></h3>
                                        <p class="comment"><a href="#">12 comments</a></p>
                                        <p>Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque</p>
                                    </article>                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->
            <!--******************************************
                             MAIN FROMBLOG END
              ******************************************-->      
        </main>
        <!--******************************************
        **********************************************
                            MAIN END
        *********************************************
        *********************************************-->