<?php
Zend_Layout::getMvcInstance()->disableLayout();

$membersTotal = $this->membersTotal;
$membersActive = $this->membersActive;

?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-table fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <div class="huge"><?php echo $this->escape($membersTotal) . ' / ' . $this->escape($membersActive);?></div>
                <div>Members total / active</div>
            </div>
        </div>
    </div>
    <a href="<?php echo $this->url(array('controller' => 'admin_members'), 'default', true);?>">
        <div class="panel-footer">
            <span class="pull-left">View Details</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
        </div>
    </a>
</div>