<?php
$this->headTitle('Books');
?>
<div class="page-header">
    <h1>Books</h1>
</div>
<div class="row">
    <div class="coll-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="coll-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <button data-action="save-order" class="btn btn-success" style="display: none;"><i class="glyphicon glyphicon-save"></i> Save order</button>
                    <button data-action="toggle-sort" class="btn btn-default"><i class="glyphicon glyphicon-list"></i> Change order</button>
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'add'), 'default', true) ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add Book</a>
                </div>
            </div>
            <div class="panel-body">
                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">Img</th>
                            <th class="text-center">Status</th>
                            <th class="text-center">Sale</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>ISBN</th>
                            <th>Category</th>
							<th>Price</th>
                            <th>Format</th>
                            <th class="text-center">Number of Pages</th>
                            <th class="text-center">Date of Publication</th>
                            <th>Cover</th>
                            <th>Language</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                                <?php
                                foreach ($this->books as $book) {
                                    if ($book['status'] == Application_Model_DbTable_CmsBooks::STATUS_ENABLED) {
                                        ?>
                                <tr data-book-id="<?php echo $this->escape($book['id']); ?>">
                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor: pointer;"></i></td>
                                    <td class="text-center"><img style="max-height: 50px;" src="<?php echo $this->bookImgUrl($book); ?>"></td>
                                    <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
								<?php if($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) {?>
									<td class="text-center"><span class="badge alert-success" title="on-sale"><i class="glyphicon glyphicon-ok"></i></span></td>
								<?php } else {?>
									<td class="text-center"><span class="badge alert-danger" title="not-on-sale"><i class="glyphicon glyphicon-remove"></i></span></td>
								<?php }?>
                                    <td><?php echo $this->escape($book['title']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['author_id']); ?></td>
                                    <td><?php echo $this->escape($book['isbn']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['category_id']); ?></td>
                                    <td><?php echo $this->escape($book['price']); ?></td>
                                    <td><?php echo $this->escape($book['format']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['number_of_pages']); ?></td>
                                    <td><?php echo $this->escape($book['date_of_publication']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['cover_id']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['language_id']); ?></td>
                                    <td width="10%" class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a  
                                                href="<?php echo $this->bookUrl($book); ?>"
                                                target="_blank"
                                                type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>

                                            <a href="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'edit', 'id' => $book['id']), 'default', true); ?>"
                                               type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-book-id="<?php echo $this->escape($book['id']); ?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                            <button data-book-id="<?php echo $this->escape($book['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                                    <?php
                                } else {
                                    ?>
                                <tr data-book-id="<?php echo $this->escape($book['id']); ?>" class="danger">
                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor: pointer;"></i></td>
                                    <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->bookImgUrl($book); ?>"></td>
                                    <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
								<?php if($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) {?>
									<td class="text-center"><span class="badge alert-success" title="on-sale"><i class="glyphicon glyphicon-ok"></i></span></td>
								<?php } else {?>
									<td class="text-center"><span class="badge alert-danger" title="not-on-sale"><i class="glyphicon glyphicon-remove"></i></span></td>
								<?php }?>
                                    <td><?php echo $this->escape($book['title']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['author_id']); ?></td>
                                    <td><?php echo $this->escape($book['isbn']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['category_id']); ?></td>
                                    <td><?php echo $this->escape($book['price']); ?></td>
                                    <td><?php echo $this->escape($book['format']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['number_of_pages']); ?></td>
                                    <td><?php echo $this->escape($book['date_of_publication']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['cover_id']); ?></td>
                                    <td class="text-center"><?php echo $this->escape($book['language_id']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a  
                                                href="<?php echo $this->bookUrl($book); ?>"
                                                target="_blank"
                                                type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>

                                            <a  
                                                href="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'edit', 'id' => $book['id']), 'default', true); ?>"
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-book-id="<?php echo $this->escape($book['id']); ?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                            <button data-book-id="<?php echo $this->escape($book['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                                <?php
                                }
                                ?>
                            <?php
                            }
                            ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete book</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete book?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"> </i>Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Disable book</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to disable book?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"> </i> Disable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Enable book</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to enable book?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Enable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_books', 'action' => 'updateorder'), 'default', true); ?>" style="display: none;" id="save-order-form">
    <input type="hidden" name="task" value="saveOrder">
    <input type="hidden" name="sorted_ids" value="">
</form>
<?php
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css')); // osnovni kod za dodavanje CSS-a na stranicu
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js')); // osnovni kod za dodavanje JS-a na stranicu
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>

    $('#rows-table').on('click', '[data-action="delete"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        // calculate target element
        var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');

        // get any attribute
        //var bookId = target.attr('data-book-id');

        // get "data-" attributes
        var bookId = target.data('book-id');


        // set value for input field with name "id"
        $('#delete-warning-dialog').find('[name="id"]').val(bookId);

        $('#delete-warning-dialog').modal('show');

    });

    $('#rows-table').on('click', '[data-action="disable"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        // calculate target element
        var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');

        // get any attribute
        var bookId = target.attr('data-book-id');

        // get "data-" attributes
        //var bookId = target.data('book-id');


        // set value for input field with name "id"
        $('#disable-warning-dialog').find('[name="id"]').val(bookId);

        $('#disable-warning-dialog').modal('show');

    });

    $('#rows-table').on('click', '[data-action="enable"]', function (e) {

        e.preventDefault();
        e.stopPropagation();

        // calculate target element
        var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');

        // get any attribute
        var bookId = target.attr('data-book-id');

        // get "data-" attributes
        //var bookId = target.data('book-id');


        // set value for input field with name "id"
        $('#enable-warning-dialog').find('[name="id"]').val(bookId);

        $('#enable-warning-dialog').modal('show');

    });

    $('[data-action="toggle-sort"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');

        var sortableTbody = $('#rows-table > tbody');

        if (target.hasClass('active')) {

            target.removeClass('active');

            target.html('<i class="glyphicon glyphicon-list"></i> Change order');

            // destroy sortable funcionality
            sortableTbody.sortable('destroy');

            // restore old html into tbody
            sortableTbody.html(sortableTbody.data('oldHtml'));

            // hide "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').hide();

            // hide "Save Order" button
            $('[data-action="save-order"]').hide();

        } else {

            target.addClass('active');

            // method html sets or gets html inside selected element
            target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');

            // save tbody html before sorting under key "oldHtml" into its data
            sortableTbody.data('oldHtml', sortableTbody.html());

            // initialize sortable functionality
            sortableTbody.sortable({
                handle: '[data-action="sort"]'
            });

            // show "handle" for sorting, the icon in first column
            sortableTbody.find('[data-action="sort"]').show();

            // show "Save Order" button
            $('[data-action="save-order"]').show();

        }
    });

    $('[data-action="save-order"]').on('click', function (e) {

        e.preventDefault();
        e.stopPropagation();

        var bookSortedIds = $('#rows-table > tbody').sortable('toArray', {
            attribute: 'data-book-id'
        });

        var saveOrderForm = $('#save-order-form');

        // find element with name "sorted_ids" in save order form and set its value
        // with string in wich are sorted ids separated with coma (,)
        // ex. "12,3,8,10,11,6,2,1,9,7,5,4"
        saveOrderForm.find('[name="sorted_ids"]').val(bookSortedIds.join(','));

        // manually submit form by triggering "submit" event
        saveOrderForm.trigger('submit');

    });

<?php $this->inlineScript()->captureEnd(); ?>
</script>

