<?php

/*** treba da naslov u tabu u browseru bude Naslov Foto Galerije | Foto Galerije | Cubes CMS ***/
$this->headTitle($this->sitemapPage['title']);
$this->headTitle($this->photoGallery['title']);

$this->headMeta()->appendName('description', $this->photoGallery['description']);
?>

		<main>
			
		<?php echo $this->breadCrumbsHtml($this->sitemapPage['id']);?>

            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
						<?php foreach($this->photos as $photo) {;?>
						<div class="col-sm-4">
						<div class="blogLists spacing">                          
							<a href="#" blog-img><img src="<?php echo $this->photoUrl($photo);?>" alt="" class="center-block img-responsive"/></a>
							
						</div>
						</div>
						
						<?php }?>
						
					</div>
				</div>
			</div>
        </main>