<?php

$this->headTitle('Services');

?>
<div class="page-header">
  <h1>Services</h1>
</div>
<div class="row">
    <div class="coll-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
    </div>
</div>
<div class="row">
    <div class="coll-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <button data-action="save-order" class="btn btn-success" style="display: none;"><i class="glyphicon glyphicon-save"></i> Save order</button>
                    <button data-action="toggle-sort" class="btn btn-default"><i class="glyphicon glyphicon-list"></i> Change order</button>
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'add'), 'default', true) ?>" 
                       class="btn btn-default"
                       ><i class="glyphicon glyphicon-plus"></i> Add Service</a>
                </div>
            </div>
            <div class="panel-body">
                                <table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
                                                        <th></th>
							<th class="text-center">Icon</th>
							<th class="text-center">Status</th>
							<th>Title</th>
							<th>Descritpion</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
                                            <?php
                                            foreach ($this->services as $service) {
                                                if ($service['status'] == Application_Model_DbTable_CmsServices::STATUS_DISABLED) {
                                                ?>
                                            <tr data-service-id="<?php echo $this->escape($service['id']);?>" class="danger">
                                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor: pointer;"></i></td>
                                                    <td class="text-center"><i class="<?php echo $this->escape($service['icon']);?> icon-small icon-inverse-80 _icon-circle"></i></td>
                                                    <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                                                    <td><?php echo $this->escape($service['title']); ?></td>
                                                    <td><?php echo $this->escape($service['description']); ?></td>
                                                    <td class="text-center">
                                                            <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                                                <a  
                                                                        href="<?php echo $this->url(array ('controller' => 'admin_services', 'action' => 'edit', 'id' => $service['id']), 'default', true); ?>"
                                                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                                                <button data-service-id="<?php echo $this->escape($service['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                                                <button data-service-id="<?php echo $this->escape($service['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                                            </div>
                                                    </td>
                                            </tr>
                                            
                                            <?php
                                                } else {
                                            ?>
                                            <tr data-service-id="<?php echo $this->escape($service['id']);?>">
                                                    <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor: pointer;"></i></td>
                                                    <td class="text-center"><i class="<?php echo $this->escape($service['icon']);?> icon-small icon-inverse-80 _icon-circle"></i></td>
                                                    <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                                                    <td><?php echo $this->escape($service['title']); ?></td>
                                                    <td><?php echo $this->escape($service['description']); ?></td>
                                                    <td class="text-center">
                                                            <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                                                <a href="<?php echo $this->url(array ('controller' => 'admin_services', 'action' => 'edit', 'id' => $service['id']), 'default', true); ?>"
                                                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                                                <button data-service-id="<?php echo $this->escape($service['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                                                <button data-service-id="<?php echo $this->escape($service['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                                            </div>
                                                    </td>
                                            </tr>
                                            <?php
                                                }
                                            ?>
                                            
                                            <?php
                                            }
                                            ?>
						
					</tbody>
				</table>
            </div>
        </div>
    </div>
</div>

<form method="post" action="<?php echo  $this->url(array('controller' => 'admin_services', 'action' => 'delete'), 'default', true);?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="deleteservice">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"> </i>Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo  $this->url(array('controller' => 'admin_services', 'action' => 'disable'), 'default', true);?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disableservice">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"> </i> Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo  $this->url(array('controller' => 'admin_services', 'action' => 'enable'), 'default', true);?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enableservice">
    <input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'updateorder'), 'default', true);?>" style="display: none;" id="save-order-form">
    <input type="hidden" name="task" value="saveOrderServices">
    <input type="hidden" name="sorted_ids_services" value="">
</form>
<?php

$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css')); // osnovni kod za dodavanje CSS-a na stranicu
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js')); // osnovni kod za dodavanje JS-a na stranicu
        
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>    

   $('#rows-table').on('click', '[data-action="delete"]', function (e) {
       
       e.preventDefault();
       e.stopPropagation();
       
       // calculate target element
       var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
       
       // get any attribute
      var serviceId = target.attr('data-service-id');
       
       // set value for input field with name "id"
       $('#delete-warning-dialog').find('[name="id"]').val(serviceId);
       
       $('#delete-warning-dialog').modal('show');
       
   });
   
   $('#rows-table').on('click', '[data-action="disable"]', function (e) {
       
       e.preventDefault();
       e.stopPropagation();
       
       // calculate target element
       var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
       
      var serviceId = target.data('service-id');
       
       // set value for input field with name "id"
       $('#disable-warning-dialog').find('[name="id"]').val(serviceId);
       
       $('#disable-warning-dialog').modal('show');
       
   });
   
   $('#rows-table').on('click', '[data-action="enable"]', function (e) {
       
       e.preventDefault();
       e.stopPropagation();
       
       // calculate target element
       var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
       
       // get any attribute
      var serviceId = target.attr('data-service-id');
       
       // set value for input field with name "id"
       $('#enable-warning-dialog').find('[name="id"]').val(serviceId);
       
       $('#enable-warning-dialog').modal('show');
       
   });

    $('[data-action="toggle-sort"]').on('click', function (e) {
      
       e.preventDefault();
       e.stopPropagation();
       
       var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');
       
       var sortableTbody = $('#rows-table > tbody');
       
       if (target.hasClass('active')) {
           
           target.removeClass('active');
           
           target.html('<i class="glyphicon glyphicon-list"></i> Change order');
           
           // destroy sortable funcionality
           sortableTbody.sortable('destroy');
           
           // restore old html into tbody
           sortableTbody.html(sortableTbody.data('oldHtml'));
           
           // hide "handle" for sorting, the icon in first column
           sortableTbody.find('[data-action="sort"]').hide();
           
           // hide "Save Order" button
           $('[data-action="save-order"]').hide();
           
       } else {
           
           target.addClass('active');
           
           // method html sets or gets html inside selected element
           target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
           
           // save tbody html before sorting under key "oldHtml" into its data
           sortableTbody.data('oldHtml', sortableTbody.html());
           
           // initialize sortable functionality
           sortableTbody.sortable({
                handle: '[data-action="sort"]'
            });
           
           // show "handle" for sorting, the icon in first column
           sortableTbody.find('[data-action="sort"]').show();
           
           // show "Save Order" button
           $('[data-action="save-order"]').show();
           
       }
   });
   
   $('[data-action="save-order"]').on('click', function (e) {
        
        e.preventDefault();
        e.stopPropagation();
        
        var serviceSortedIds = $('#rows-table > tbody').sortable('toArray', {
            attribute: 'data-service-id'
        });
        
        var saveOrderForm = $('#save-order-form');
        
        saveOrderForm.find('[name="sorted_ids_services"]').val(serviceSortedIds.join(','));
        
        saveOrderForm.trigger('submit');
        
   });
<?php $this->inlineScript()->captureEnd(); ?>  
</script>

