<?php

$this->headTitle($this->author['name'] . ' | ' . $this->sitemapPage['title'])

?>
        <main class="bookMain">

        <?php echo $this->breadCrumbsHtml($this->sitemapPage['id']);?>

            <div class="container">
                <div class="row">
                    <div class="col-sm-3 col-lg-2 leftArticle">
                        <article>
                            <a href="javascript:void(0)"><p class="text-center artArchitecturePhotography">Art, Architecture & Photography<span class="fa fa-cog"></span></p>
                            </a>
                            <div class="lists">
                                <h3 class="text-center">All Authors</h3>
                                <ul class="text-center list-unstyled">
                                    <?php foreach ($this->authors as $author) {?>
                                    <li><a href="<?php echo $this->authorUrl($author);?>"><?php echo $this->escape($author['name']);?></a></li>
                                    <?php }?>
                                </ul>
                            </div>
                        </article>
                    </div>

                    <div class="col-sm-9 col-lg-10">
                        <article>
                            <div class="row">
                                <div class="col-md-6">
                                    <article>
                                        <img src="<?php echo $this->authorImgUrl($this->author);?>" class="bigOrangeBook center-block" height="429" width="303">
                                        <hr>
                                        <img class="secondImage center-block" src="/front/img/socialNetworks.png">

                                    </article>
                                </div>
                                <div class="col-md-6">
                                    <article>

                                        <div class="inspirationSpeaks">
                                            <h2><?php echo $this->escape($this->author['name']);?></h2>
                                            
                                            <div class="pharagraphas">
                                            <?php echo $this->escape($this->author['about']);?>    
                                            </div>


                                        </div>
                                    </article>
                                </div>
                            </div>
                        </article>


                        <div class="smallBooks">
                            <div class="bestsellers clearfix text-center">
                                <div class="relatedProducts">
                                    <h2>Books Of This Author</h2>
                                </div>
                                <div class="arrowRight">
                                </div>
                                <?php
								foreach ($this->relatedBooks as $book) {
									if ($book['sale'] == Application_Model_DbTable_CmsBooks::ON_SALE) {
										?>
										<div class="books">
											<figure class="center-block">
												<a href="<?php echo $this->bookUrl($book); ?>"><img src="<?php echo $this->bookImgUrl($book); ?>" class="img-responsive"></a>
												<span class="sale">SALE</span>
											</figure>
											<h4 class="down"><a href="<?php echo $this->bookUrl($book); ?>"><b><?php echo $this->escape($book['title']); ?></b></a></h4>
											<p><span class="by">by</span> Stephen King</p>
											<p class="prise center-block"><?php echo $this->escape($book['price']); ?><!--<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a>--></p>
										</div>
										<?php } else {
										?>
										<div class="books">
											<figure class="center-block">
												<a href="<?php echo $this->bookUrl($book); ?>"><img src="<?php echo $this->bookImgUrl($book); ?>" class="img-responsive"></a>
											</figure>
											<h4 class="down"><a href="<?php echo $this->bookUrl($book); ?>"><b><?php echo $this->escape($book['title']); ?></b></a></h4>
											<p><span class="by">by</span> Stephen King</p>
											<p class="prise center-block"><?php echo $this->escape($book['price']); ?><!--<a href="#" class="shop"><span><span class="fa fa-plus"></span><span class="fa fa-shopping-basket"></span></span></a>--></p>
										</div>
									<?php }
								} ?>
                            </div>
                        </div>
                    </div>


                </div>
<!--                <h3 class="text-center customerReviews3"><b>Customer Reviwes (3)</b></h3>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle" src="/front/img/member2.png">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><b>Hezy Theme</b> <span class="by">21 Jul, 2105 3:34 pm</span></h4>
                        <p class="text-justify">I have a jQuery diamond wipe animation plugin that works on much the same principles - just need to find the time to write it up and publish it.Again, the result of a designer making crazy demands, but it's pleasantly surprising how much we can do today, where once all you could say was "I'm sorry.</p>
                        <a href="#">Reply</a>
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle" src="/front/img/member1.png">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><b>Kris Morgan</b> <span class="by">21 Jul, 2105 3:34 pm</span></h4>
                        <p class="text-justify">Again, the result of a designer making crazy demands, but it's pleasantly surprising how much we can do today, where once all you could say was "I'm sorry the web just doesn't work like that..."Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec </p>
                        <a href="#">Reply</a>
                    </div>
                </div>
                <div class="media">
                    <div class="media-left">
                        <img class="media-object img-circle" src="/front/img/member2.png">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><b>Arsen Cox</b>  <span class="by">21 Jul, 2105 3:34 pm</span></h4>
                        <p class="text-justify">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, ali</p>
                        <a href="#">Reply</a>
                    </div>
                </div>-->
            </div>
        </main>
        <!--******************************************
        **********************************************
                        MAIN END
        *********************************************
        ******************************************-->