<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <?php echo $this->headTitle('Book Store')->setSeparator(' | ');?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
			<?php echo $this->headMeta();?>
		
        <link rel="stylesheet" href="/front/css/bootstrap.min.css">
        <link rel="stylesheet" href="/front/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/front/css/books.css">
        <link href="/front/css/main.css" rel="stylesheet" type="text/css"/>
        <link href="/front/css/responsive.css" rel="stylesheet" type="text/css"/>
			<?php echo $this->headLink();?>
		
			<?php echo $this->headStyle();?>
		
		<link rel="apple-touch-icon" href="/front/apple-touch-icon.png">
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link href='https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="http://resources/demos/style.css">
		
        <script src="/front/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
			<?php echo $this->inlineScript();?>
    </head>
    <body>

        <!--******************************************
                        HEADER START
            *****************************************-->


        <header>

            <!--******************************************
                            HEADER TOP-MENU START
            *******************************************-->
            <div class="top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <article class="top-menu-first">
                                <ul class="list-unstyled list-inline text-center">
<!--                                    <li><a data-toggle="modal" data-target="#modalPrimer" href="#">Online Store</a></li>-->
                                    <li><a href="<?php echo $this->sitemapPageUrl('1');?>"><?php echo $this->sitemapPageShortTitle('1');?></a></li>
<!--                                    <li><a href="#">Delivery</a></li>
                                    <li><a href="#">FAQS</a></li>-->
                                    <li><a href="<?php echo $this->sitemapPageUrl('12');?>"><?php echo $this->sitemapPageShortTitle('12');?></a></li>
                                </ul>
                            </article>
                        </div>
                        <div class="col-md-6">
                            <article class="text-center top-menu-second">
                                <span class=" glyphicon glyphicon-earphone"></span>
                                <p>+1-234-567-8901</p>
                            </article>
                        </div>
<!--                        <div class="col-md-4">
                            <article class="top-menu-third">-->
<!--                                <ul class="list-unstyled list-inline text-center">
                                    <li><a href="login.html">Login</a></li>
                                    <li><a href="register.html">Registracija</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Profile</a></li>
                                            <li><a href="#">My Shop</a></li>
                                            <li><a href="#">Log Out</a></li>
                                        </ul>
                                    </li>
                                </ul>-->
<!--                            </article>
                        </div>-->
                    </div>
                </div>
            </div>

            <!--******************************************
                            HEADER TOP-MENU END
                *****************************************-->


            <!--******************************************
                            HEADER HEADER-MIDDLE START
            ********************************************-->
            <div class="header-middle">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <article class="middle-first">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                                    </span>
                                </div>
                            </article>
                        </div>
                        <div class="col-xs-6 col-md-4">
                            <article class="text-left middle-second">
                                <h1>BookShop</h1>
<!--                                <p>World of books</p>-->
                            </article>
                        </div>
<!--                        <div class="col-xs-6 col-md-4 ">
                            <div class="row">
                                <div class="col-sm-6 delivery">
                                    <article class="text-center">
                                        <ul class="list-inline">
                                            <li><img src="/front/img/iconDekivery.png" alt=""/></li>
                                            <li><p>Free delivery</p></li>
                                        </ul>                                                                  
                                    </article>
                                </div>
                                <div class="col-sm-12 col-md-6 ">
                                    <article class="text-center middle-third">
                                        <ul class="list-inline">
                                            <li>
                                                <p class="price">$345.39</p>
                                                <p class="items">2 items</p>
                                            </li>
                                            <li><a href="#"><img src="/front/img/cart.png" alt="" id="myCart" class="cart"/></a></li>
                                        </ul>
                                    </article>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>
            </div>

            <!--******************************************
                            HEADER HEADER-MIDDLE END
            *******************************************-->



            <!--******************************************
                            HEADER NAVIGATION START
            *******************************************-->
            <div class="menu">
                <nav class="navbar">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <?php echo $this->topMenuHtml();?>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </div>

            <!--******************************************
                            HEADER NAVIGATION START
                *****************************************-->

        </header>

        <!--******************************************
                            HEADER END
          *****************************************-->



        <?php echo $this->layout()->content;?>




        <!--******************************************
        **********************************************
                        
                        FOOTER START
        *********************************************
        *********************************************-->
        <footer>
            <!--******************************************
                            FOOTER TOP START
              ******************************************-->
            <section class="footerTop">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <article>
                                <h4>ABOUT THIS SITE</h4>
                                <p><img src="/front/img/aboutFooterLogo.png" class="pull-left logoFoot" >A cras tincidunt, ut tellus et. Gravida scele risque, ipsum sed iacul is, nunc non namtellus. Placerat sed phasellus, purus purus elit. Cras ante eros. Erat vel. Donec vestibulum sed, vel euimsod donec. </p>                       
                            </article>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <article>
                                <h4>CATEGORIES</h4>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <article>
                                            <p><a href="#">Books</a></p>
                                            <p><a href="#">Text books</a></p>
                                            <p><a href="#">Nook books</a></p>
                                            <p><a href="#">Audio books</a></p>
                                            <p><a href="#">Magazines</a></p>
                                        </article>
                                    </div>
                                    <div class="col-sm-6">
                                        <article>
                                            <p><a href="#">Movies</a></p>
                                            <p><a href="#">Music</a></p>
                                            <p><a href="#">Games</a></p>
                                        </article>
                                    </div>
                                </div>
                            </article>
                        </div>
                        <div class="col-md-3 col-sm-6">
<!--                            <article>
                                <h4>INFORMATION</h4>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <article>
                                            <p><a href="#">Track Order</a></p>
                                            <p><a href="#">Delvery</a></p>
                                            <p><a href="#">Return Policy</a></p>
                                            <p><a href="#">GIFcards</a></p>                                        
                                        </article>
                                    </div>
                                    <div class="col-sm-6">
                                        <article>
                                            <p><a href="#">Contact Us</a></p>
                                            <p><a href="#">Strory Locations</a></p>
                                            <p><a href="#">FAQ</a></p>
                                            <p><a href="#">Terms of Use</a></p>
                                        </article>
                                    </div>
                                </div>
                            </article>-->
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <article>
                                <h4>CONECT</h4>
                                <p class="socialNetworks">
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-pinterest-p"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-rss"></span></a>
                                    <a href="#"><span class="fa fa-instagram"></span></a>
                                </p>
                                <p class="subscribe">Subscribe to our weekly newsletter.</p>
                                <form class="form-group">
                                    <input type="email" placeholder="Email Address"/>
                                    <button>SUBSCRIBE</button>
                                </form>
                            </article>
                        </div>
                    </div>

                </div>
            </section>
            <!--*****************************************
                            FOOTER TOP END
              ******************************************-->



            <!--****************************************
                          FOOTER DOWN START
            ******************************************-->
            <section class="footerDown">
                <div class="container">
                    <div class="row line">
                        <div class="col-sm-6">
                            <article>
                                <p>
                                    <a href="#"><span class="fa fa-cc-visa"></span></a>
                                    <a href="#"><span class="fa fa-cc-mastercard"></span></a>
                                    <a href="#"><span class="fa fa-cc-paypal"></span></a>
                                    <a href="#"><span class="fa fa-cc-amex"></span></a>
                                    <a href="#"><span class="fa fa-cc-visa"></span></a>
                                    <a href="#"><span class="fa fa-cc-amex"></span></a>
                                    <a href="#"><span class="fa fa-cc-mastercard"></span></a>
                                    <a href="#"><span class="fa fa-cc-jcb"></span></a>
                                    <a href="#"><span class="fa fa-cc-amex"></span></a>
                                    <a href="#"><span class="fa fa-cc-amex"></span></a>
                                </p>
                            </article>
                        </div>
                        <div class="col-sm-6">
                            <article>
                                <p class="copyRight">&copy;2014 BOOKSHOP.ALL RIGHTS. RESERVED.</p>
                                <p class="madeBy">MADE WITH BY <a href="#" class="firm">HEZHTHEME</a></p>
                                <a class="top" href="#">TOP <span class="fa fa-caret-up"></span></a>
                            </article>
                        </div>
                    </div>
                    <p class="text-center developer">Ovaj projekat je realizovan u okviru <a href="http://school.cubes.rs">CUBES SCHOOL</a>. Projekat realozovali: FRONTEND - <a href="#">Nikola Popovic</a> BACKEND - <a href="#">Aleksandar Stevanović</a></p>
                </div>
            </section>
            <!--******************************************
                            FOOTER DOWN END
              ******************************************-->
        </footer>
        <!--******************************************
        **********************************************
                          FOOTER END
        *********************************************
        *********************************************-->
        <div class="modal fade" id="modalPrimer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <h4>Text in a modal</h4>
                        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p> 
                        <h4>Popover in a modal</h4>
                        <p>This <a data-original-title="A Title" href="#" class="btn btn-default popover-test" role="button" title="" data-content="And here's some amazing content. It's very engaging. right?">button</a> should trigger a popover on click.</p> 
                        <h4>Tooltips in a modal</h4> 
                        <p><a data-original-title="Tooltip" href="#" class="tooltip-test" title="">This link</a> and <a data-original-title="Tooltip" href="#" class="tooltip-test" title="">that link</a> should have tooltips on hover.</p> 
                        <hr> 
                        <h4>Overflowing text to show scroll behavior</h4> 
                        <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p> 
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p> 
                        <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p> 
                        <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p> 
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p> 
                        <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p> 
                        <p>Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p> 
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p> 
                        <p>Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla.</p> 
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="second center-block">
            <table class="table table-responsive">
                <tbody>
                    <tr> 
                        <td>
                            <figure>
                                <a href="#"><img src="/front/img/pictureForBoxCartt.png" alt="" class="img-responsive" /></a> 
                            </figure>
                        </td>
                        <td>3497,00</td> 
                        <td>2</td> 
                        <td><a href="#javascript:void(0)" class="remove">X</a></td>
                    </tr> 
                    <tr> 
                        <td>
                            <figure>
                                <a href="#"><img src="/front/img/pictureForBoxCartt.png" alt="" class="img-responsive" /></a> 
                            </figure> 
                        </td>

                        <td>1679,00</td> 
                        <td>1</td> 
                        <td><a href="#javascript:void(0)" class="remove">X</a></td>
                    </tr> 
                    <tr> 
                        <td>
                            <figure>
                                <a href="#"><img src="/front/img/pictureForBoxCartt.png" alt="" class="img-responsive" /></a> 
                            </figure> 
                        </td> 
                        <td>400,00</td> 
                        <td>1</td> 
                        <td><a href="#javascript:void(0)" class="remove">X</a></td>
                    </tr> 
                </tbody>
                <tfoot>
                    <tr class="lastRow"> 
                        <td colspan="2">
                            Total:  <span>5413,87</span>
                        </td> 
                        <td colspan="2">
                            <a href="#">KUPI</a>
                        </td>

                    </tr> 
                </tfoot>
            </table>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.js"><\/script>')</script>

        <script src="/front/js/vendor/bootstrap.min.js"></script>
        <script src="/front/js/validator.js" type="text/javascript"></script>
        <script src="/front/js/main.js"></script>
		<?php echo $this->inlineScript();?>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function (b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function () {
                            (b[l].q = b[l].q || []).push(arguments)
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
            }(window, document, 'script', 'ga'));
            ga('create', 'UA-XXXXX-X', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>
