<!--******************************************
                        MAIN START
        *******************************************-->
        <main>
            <ol class="breadcrumb text-center blogPostBorder">
                <li><a href="#">Home</a></li>
                <li><b>Blog</b></li>
            </ol>

            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <article>
                            <div class="blogLists">                          
                                <a href="#" blog-img><img src="/front/img/blogMainImage.png" alt="" class="center-block img-responsive"/></a>
                                <div class="spacing">                                 
                                <a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a>
                                <p>
                                    <span class="fa fa-user"> Hezy Theme</span>
                                    <span class="fa fa-calendar-o"> 12 Jul, 2015</span>
                                    <span class="fa fa-comment"> 42 Comments</span>
                                </p>
                                <p>Phasellus viverra nulla ut metus varius laoreet. 
                                    Quisque rutrum. Aenean imperdiet. Etiam ultricies
                                    nisi vel augue. Curabitur ullamcorper ultricies 
                                    nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus,
                                    tellus eget condimentum rhoncus, sem quam semper
                                    libero, sit amet adipiscing sem neque.  
                                    <a href="#" class="continue">Continue Reading →</a></p>
                                </div>
                            </div>

                            <div class="blogLists">
                                <a href="#"><img src="/front/img/blogSecondImagee.png" alt="" class="center-block img-responsive"/></a>
                               <div class="spacing">
                               <a href="#">Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</a>
                                <p>
                                    <span class="fa fa-user"> Bookstore</span>
                                    <span class="fa fa-calendar-o"> 6 Jul, 2015</span>
                                    <span class="fa fa-comment"> 12 Comments</span>
                                </p>
                                <p>Aenean vulputate eleifend tellus. Aenean leo ligula,
                                    porttitor eu, consequat vitae, eleifend ac, enim.
                                    Aliquam lorem ante, dapibus in, viverra quis, 
                                    feugiat a, tellus. Phasellus viverra nulla ut 
                                    metus varius laoreet. Quisque rutrum. Aenean 
                                    imperdiet. Etiam ultricies nisi vel augue. Curabitur
                                    ullamcorper ultricies nisi. Nam eget dui. Etiam 
                                    rhoncus.  
                                    <a href="#" class="continue">Continue Reading →</a></p>
                                </div>
                                
                            </div>

                            <div class="blogLists">
                                <a><img src="/front/img/blogSecondImage.png" alt="" class="center-block img-responsive"/></a>
                                <div class="spacing">
                                <a href="#">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</a>
                                <p>
                                    <span class="fa fa-user"> Hezy Theme</span>
                                    <span class="fa fa-calendar-o"> 12 Jul, 2015</span>
                                    <span class="fa fa-comment"> 42 Comments</span>
                                </p>
                                <p>Phasellus viverra nulla ut metus varius laoreet. 
                                    Quisque rutrum. Aenean imperdiet. Etiam ultricies
                                    nisi vel augue. Curabitur ullamcorper ultricies 
                                    nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus,
                                    tellus eget condimentum rhoncus, sem quam semper
                                    libero, sit amet adipiscing sem neque.  
                                    <a href="#" class="continue">Continue Reading →</a></p>
                                </div>
                               
                            </div>

                            <div class="blogLists">
                                <a href="#"><img src="/front/img/blogImage4.png" alt="" class="center-block img-responsive"/></a>
                                <div class="spacing">
                                     <a href="#">Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</a>
                                <p>
                                    <span class="fa fa-user"> Bookstore</span>
                                    <span class="fa fa-calendar-o"> 6 Jul, 2015</span>
                                    <span class="fa fa-comment"> 12 Comments</span>
                                </p>
                                <p>Aenean vulputate eleifend tellus. Aenean leo ligula,
                                    porttitor eu, consequat vitae, eleifend ac, enim.
                                    Aliquam lorem ante, dapibus in, viverra quis, 
                                    feugiat a, tellus. Phasellus viverra nulla ut 
                                    metus varius laoreet. Quisque rutrum. Aenean 
                                    imperdiet. Etiam ultricies nisi vel augue. Curabitur
                                    ullamcorper ultricies nisi. Nam eget dui. Etiam 
                                    rhoncus.  
                                    <a href="#" class="continue">Continue Reading →</a></p>
                                </div>
                               
                            </div>

                            <div class="blogLists">
                                <a href="#"><img src="/front/img/blogImage5.png" alt="" class="center-block img-responsive"/></a>
                                <div class="spacing">
                                <a href="#">Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</a>
                                <p>
                                    <span class="fa fa-user"> Bookstore</span>
                                    <span class="fa fa-calendar-o"> 6 Jul, 2015</span>
                                    <span class="fa fa-comment"> 12 Comments</span>
                                </p>
                                <p>Aenean vulputate eleifend tellus. Aenean leo ligula,
                                    porttitor eu, consequat vitae, eleifend ac, enim.
                                    Aliquam lorem ante, dapibus in, viverra quis, 
                                    feugiat a, tellus. Phasellus viverra nulla ut 
                                    metus varius laoreet. Quisque rutrum. Aenean 
                                    imperdiet. Etiam ultricies nisi vel augue. Curabitur
                                    ullamcorper ultricies nisi. Nam eget dui. Etiam 
                                    rhoncus.  
                                    <a href="#" class="continue">Continue Reading →</a></p>
                                </div>
                               
                            </div>
                        </article>
                    </div>
                    <div class="col-sm-3 sideBar">
                        <article>
                            <div>
                                <h3>Social</h3>
                                <p class="socialNetworks">
                                    <a href="#"><span class="fa fa-facebook"></span></a>
                                    <a href="#"><span class="fa fa-pinterest-p"></span></a>
                                    <a href="#"><span class="fa fa-linkedin"></span></a>
                                    <a href="#"><span class="fa fa-twitter"></span></a>
                                    <a href="#"><span class="fa fa-google-plus"></span></a>
                                    <a href="#"><span class="fa fa-rss"></span></a>
                                    <a href="#"><span class="fa fa-instagram"></span></a>
                                </p>
                            </div>

                            <div class='popularPost'>
                                <h3>Popular post</h3>
                                <div class="media">
                                    <div class="media-left spaner">
                                        <a href="#">
                                            <span class="calendar">02 APR</span>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a href="#">Corso completo di grafica web: dare...</a></h4>
                                        <span class="by"><a href="#">5 comments</a></span>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left spaner">
                                        <a href="#">
                                            <span class="calendar">23 MAR</span>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a href="#">Corso completo di grafica web: dare...</a></h4>
                                        <span class="by"><a href="#">13 comments</a></span>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left spaner">
                                        <a href="#">
                                           <span class="calendar">05 FEB</span>
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a href="#">Corso completo di grafica web: dare...</a></h4>
                                        <span class="by"><a href="#">55 comments</a></span>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <h3>ABOUT THIS SITE</h3>
                                <p><img src="/front/img/imageSideBar.png" class="pull-left logoFoot" >A cras tincidunt, ut tellus et. Gravida scele risque, ipsum sed iacul is, nunc non namtellus. Placerat sed phasellus, purus purus elit. Cras ante eros. Erat vel. Donec vestibulum sed, vel euimsod donec. </p>                                           
                            </div>

                            <div class="meta-elements">
                                <h3>Meta</h3>
                                <p><a href="#">Side Admin</a></p>
                                <p><a href="#">Log Out</a></p>
                                <p><a href="#">Entries RSS</a></p>
                                <p><a href="#">Comments RSS</a></p>
                                <p><a href="#">WordPress.org</a></p>    
                            </div>

                            <div class="categories-aside">
                                <h3>Categories</h3>
                                <p><a href="#">New Entreies (38)</a></p>
                                <p><a href="#">Cotton Sweat (15)</a></p>
                                <p><a href="#">Trends (22)</a></p>
                                <p><a href="#">Women Fashion (13)</a></p>
                                <p><a href="#">Hollywood Style</a></p>
                                <p><a href="#">90's (6)</a></p>    
                                <p><a href="#">Regular Fit (32)</a></p>    
                            </div>

                            
                        </article>
                    </div>
                </div>
                <div class='freeShiping text-center'>
                                <h3><b>Free shipping on all orders over  $75</b></h3>
                                <p>*Free over $150 for international orders</p>
                            </div>
            </div>

        </main>
        <!--******************************************
        **********************************************
                            MAIN END
        *********************************************
        *********************************************-->

